<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-VAQKFJ2" failures="1" tests="1" name="com.qa.tests.UserSignUpSuite" time="23.190" errors="0" timestamp="25 Apr 2024 10:17:14 GMT" skipped="0">
  <testcase classname="com.qa.tests.UserSignUpSuite" name="TC_RF_001_VerifyWhetherTheUserABleToRegisterInParaBankApplicationWithValidTestData" time="23.190">
    <failure message="User is not able to complete SignUp Process" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: User is not able to complete SignUp Process
at org.testng.Assert.fail(Assert.java:96)
at com.qa.pageObjects.SignUpPage.verifyUserSuccessfullyCompletedSignUpProcess(SignUpPage.java:172)
at com.qa.tests.UserSignUpSuite.TC_RF_001_VerifyWhetherTheUserABleToRegisterInParaBankApplicationWithValidTestData(UserSignUpSuite.java:51)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- TC_RF_001_VerifyWhetherTheUserABleToRegisterInParaBankApplicationWithValidTestData -->
</testsuite> <!-- com.qa.tests.UserSignUpSuite -->
